name: "Publish site"
on:
  # Run only when pushing to master branch
  push:
    branches:
      - master
jobs:
  ema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.TOKEN }}
      - name: Build sources & site 🔧
        run: |
          nix build .#site-github -j 4
      - name: Deploy to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./result/
          cname: brocco.site
